### ISSUE TITLE
Not possible to add notification message without specifying nbmdir

### ISSUE THREAD

**Issue by marpet** [senbox-org/update-center#1]
Just wanted to add a notification to the updatecenter.
That's what I did on the command line

`>~$ sudo /opt/snap/update-center/deploy_nbm.py --release 2.0 --notif "Dear User, SNAP 3.0 has been released." --notifurl http://step.esa.int/main/download/ --repo snap
`
As a result I got the following error:

```
2016-03-31 12:59:15,401 - INFO: Checking input...
Traceback (most recent call last):
  File "/opt/snap/update-center/deploy_nbm.py", line 300, in <module>
    main()
  File "/opt/snap/update-center/deploy_nbm.py", line 292, in main
    check_input(args)
  File "/opt/snap/update-center/deploy_nbm.py", line 52, in check_input
    raise argparse.ArgumentTypeError("Missing [nbmdir] argument")
argparse.ArgumentTypeError: Missing [nbmdir] argument

```

Would be good if this could be done with the nbmdir.

**Comment by julienmalik** [comment]
you're right, I did not think about this use case when writing the code

**Comment by julienmalik** [comment]
```
# /opt/snap/update-center/deploy_nbm.py --release 2.0 --notif "SNAP 3.0 has been released. Please update !" --notifurl http://step.esa.int/main/download/ --repo snap 
2016-03-31 15:53:14,554 - INFO: Checking input...
2016-03-31 15:53:14,555 - INFO: [nbmdir] argument not set
2016-03-31 15:53:14,555 - INFO: Creating /var/www/updatecenter/2.0_20160331-155314
2016-03-31 15:53:17,589 - INFO: No nbm to deploy
2016-03-31 15:53:17,770 - INFO: Generated updates.xml validates DTD successfully
```
